name: salsa
channels:
  - http://repo.radiomics.vhio.net:9080/conda/public-conda/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.9.9=h06a4308_0
  - expat=2.7.1=h6a678d5_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py310hacdc0fc_0
  - mkl_fft=1.3.11=py310hacdc0fc_1
  - mkl_random=1.2.8=py310h2fd27a0_1
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.18=hd6dcaed_0
  - pandas-stubs=2.2.3.250308=py310h06a4308_0
  - pip=25.2=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.10.18=h1a3bd86_0
  - readline=8.3=hc2a1206_0
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2022.0.0=hdb19cb5_0
  - tbb-devel=2022.0.0=hdb19cb5_0
  - tk=8.6.15=h54e0aa7_0
  - types-pytz=2025.2.0.20250809=py310h06a4308_0
  - wheel=0.45.1=py310h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - acvl-utils==0.2.5
      - argparse==1.4.0
      - asttokens==2.0.5
      - batchgenerators==0.25.1
      - batchgeneratorsv2==0.2.3
      - beautifulsoup4==4.13.4
      - blosc2==3.3.2
      - bs4==0.0.2
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - comm==0.2.1
      - connected-components-3d==3.23.0
      - contourpy==1.3.1
      - cycler==0.12.1
      - debugpy==1.8.11
      - decorator==5.1.1
      - deprecated==1.2.18
      - dicom2nifti==2.6.2
      - dynamic-network-architectures==0.3.1
      - einops==0.8.1
      - exceptiongroup==1.2.0
      - execnet==2.1.1
      - executing==0.8.3
      - fft-conv-pytorch==1.2.0
      - filelock==3.18.0
      - fonttools==4.57.0
      - fsspec==2025.3.0
      - future==1.0.0
      - gdown==4.7.1
      - glob2==0.7
      - graphviz==0.20.3
      - greenlet==3.2.3
      - idna==3.10
      - imagecodecs==2025.3.30
      - imageio==2.37.0
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - ipykernel==6.29.5
      - ipython==8.30.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.0
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - linecache2==1.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.6
      - monai==1.4.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - narwhals==1.41.0
      - natsort==8.4.0
      - ndindex==1.9.2
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - nibabel==5.3.2
      - nnunetv2==2.6.0
      - numexpr==2.10.2
      - numpy==1.25.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - opencv-python==4.8.1.78
      - optype==0.9.3
      - packaging==24.2
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.8.0
      - pillow==12.0.0
      - platformdirs==3.10.0
      - plotly==6.1.1
      - pluggy==1.5.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py-cpuinfo==9.0.0
      - pyarrow==20.0.0
      - pydicom==3.0.1
      - pygments==2.15.1
      - pylidc==0.2.3
      - pynrrd==1.1.3
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - pytest==8.3.5
      - pytest-shutil==1.8.1
      - python-dateutil==2.9.0.post0
      - python-gdcm==3.0.24.1
      - pytz==2025.1
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - requests==2.32.3
      - scikit-image==0.25.0
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - scipy-stubs==1.15.3.0
      - seaborn==0.13.2
      - setuptools==75.8.0
      - simpleitk==2.3.0
      - six==1.16.0
      - soupsieve==2.7
      - sqlalchemy==2.0.41
      - stack-data==0.2.0
      - sympy==1.13.1
      - tcia-utils==2.4.20
      - termcolor==2.5.0
      - threadpoolctl==3.6.0
      - tifffile==2025.3.13
      - tomli==2.2.1
      - torch==2.6.0
      - tornado==6.4.2
      - totalsegmentator==2.8.0
      - tqdm==4.66.1
      - traceback2==1.4.0
      - traitlets==5.14.3
      - triton==3.2.0
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - unidecode==1.4.0
      - unittest2==1.1.0
      - urllib3==2.4.0
      - vedo==2023.4.6
      - vtk==9.2.6
      - wcwidth==0.2.5
      - wrapt==1.17.2
      - xvfbwrapper==0.2.13
      - yacs==0.1.8
prefix: /nfs/home/clmbalaguer/anaconda3/envs/salsa
